{
 "title": "Nombre requête Patrimoine",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "200 Status Codes",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({app=\"nexelis_app\"} | json | statusCode >= 200 and statusCode < 300 [1h])) or vector(0)"
    }
   ]
  },
  {
   "title": "300 Status Codes",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({app=\"nexelis_app\"} | json | statusCode >= 300 and statusCode < 400 [1h]))  or vector(0)"
    }
   ]
  },
  {
   "title": "400 Status Codes",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({app=\"nexelis_app\"} | json | statusCode >= 400 and statusCode < 500 [1h])) or vector(0)"
    }
   ]
  },
  {
   "title": "500 Status Codes",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({app=\"nexelis_app\"} | json | statusCode >= 500 [1h])) or vector(0)"
    }
   ]
  },
  {
   "title": "Nexelis Patrimoine",
   "type": "logs",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 5 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"nexelis_patrimoine\"} | json | line_format `[LEVEL:{{.level}}] {{if .module}}- {{.module}}{{end}} - {{.msg}}`"
    }
   ]
  },
  {
   "title": "Nexelis Backend",
   "type": "logs",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 5 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"nexelis_app\"} | json | line_format `[LEVEL:{{.level}}] {{if .module}}- {{.module}}{{end}} - {{.msg}}`"
    }
   ]
  },
  {
   "title": "Nombre requête Backend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(method) (count_over_time({app=\"nexelis_patrimoine\"} | json | method != `` [1h]))"
    }
   ]
  },
  {
   "title": "Nombre requête Backend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (method) (count_over_time({app=\"nexelis_app\"} | json | method != \"\" [1h]))"
    }
   ]
  }
 ]
}