image: node:18

definitions:
  caches:
    pnpm: ~/.local/share/pnpm/store

pipelines:
  default:
    - step:
        name: Install dependencies
        caches:
          - pnpm
        script:
          - npm install -g pnpm
          - pnpm install --no-frozen-lockfile
        artifacts:
          - node_modules/**
          - backend/node_modules/**
          - frontend/node_modules/**
          - shared/node_modules/**

    - parallel:
        - step:
            name: Backend - Quality Check
            caches:
              - pnpm
            script:
              - npm install -g pnpm
              - cd backend
              - echo "🎨 Vérification du formatage Prettier pour le backend..."
              - pnpm prettier --check "src/**/*.{ts,js,json}" --config .prettierrc
              - echo "🔍 Vérification ESLint pour le backend..."
              - pnpm lint
              - echo "✅ Le backend est conforme"

        - step:
            name: Frontend - Quality Check
            caches:
              - pnpm
            script:
              - npm install -g pnpm
              - cd frontend
              - echo "🎨 Vérification du formatage Prettier pour le frontend..."
              - pnpm prettier --check "src/**/*.{ts,tsx,js,jsx,json,css}" --config .prettierrc
              - echo "🔍 Vérification ESLint pour le frontend..."
              - pnpm lint
              - echo "✅ Le frontend est conforme"

        - step:
            name: Shared - Quality Check
            caches:
              - pnpm
            script:
              - npm install -g pnpm
              - cd shared
              - echo "🎨 Vérification du formatage Prettier pour shared..."
              - pnpm prettier --check "**/*.{ts,js,json}" --config .prettierrc
              - echo "🔍 Vérification ESLint pour shared..."
              - pnpm lint
              - echo "✅ Le shared est conforme"

    - parallel:
        - step:
            name: Backend - TypeScript Check
            caches:
              - pnpm
            script:
              - npm install -g pnpm
              - cd backend
              - echo "🔍 Vérification TypeScript pour le backend..."
              - pnpm tsc --noEmit
              - echo "✅ Pas d'erreurs TypeScript dans le backend"

        - step:
            name: Frontend - TypeScript Check
            caches:
              - pnpm
            script:
              - npm install -g pnpm
              - cd frontend
              - echo "🔍 Vérification TypeScript pour le frontend..."
              - pnpm tsc --noEmit
              - echo "✅ Pas d'erreurs TypeScript dans le frontend"

  branches:
    main:
      - step:
          name: Install dependencies
          caches:
            - pnpm
          script:
            - npm install -g pnpm
            - pnpm install --no-frozen-lockfile
          artifacts:
            - node_modules/**
            - backend/node_modules/**
            - frontend/node_modules/**
            - shared/node_modules/**

      - parallel:
          - step:
              name: Backend - Full Check
              caches:
                - pnpm
              script:
                - npm install -g pnpm
                - cd backend
                - echo "🎨 Vérification du formatage..."
                - pnpm prettier --check "src/**/*.{ts,js,json}" --config .prettierrc
                - echo "🔍 Vérification TypeScript..."
                - pnpm tsc --noEmit
                - echo "🔍 Vérification ESLint..."
                - pnpm lint
                - echo "✅ Backend validé"

          - step:
              name: Frontend - Full Check
              caches:
                - pnpm
              script:
                - npm install -g pnpm
                - cd frontend
                - echo "🎨 Vérification du formatage..."
                - pnpm prettier --check "src/**/*.{ts,tsx,js,jsx,json,css}" --config .prettierrc
                - echo "🔍 Vérification TypeScript..."
                - pnpm tsc --noEmit
                - echo "🔍 Vérification ESLint..."
                - pnpm lint
                - echo "✅ Frontend validé"

          - step:
              name: Shared - Full Check
              caches:
                - pnpm
              script:
                - npm install -g pnpm
                - cd shared
                - echo "🎨 Vérification du formatage..."
                - pnpm prettier --check "**/*.{ts,js,json}" --config .prettierrc
                - echo "🔍 Vérification ESLint..."
                - pnpm lint
                - echo "✅ Shared validé"

      - step:
          name: Build Applications
          caches:
            - pnpm
          script:
            - echo "🔨 Construction des applications..."
            - cd backend && pnpm build
            - cd ../frontend && pnpm build
            - echo "✅ Applications construites avec succès"
          artifacts:
            - backend/dist/**
            - frontend/dist/**

  pull-requests:
    "**":
      - step:
          name: Install dependencies
          caches:
            - pnpm
          script:
            - npm install -g pnpm
            - pnpm install --no-frozen-lockfile
          artifacts:
            - node_modules/**
            - backend/node_modules/**
            - frontend/node_modules/**
            - shared/node_modules/**

      - parallel:
          - step:
              name: Backend - Code Quality
              caches:
                - pnpm
              script:
                - npm install -g pnpm
                - cd backend
                - echo "🔍 Vérification de la qualité du code backend..."
                - pnpm prettier --check "src/**/*.{ts,js,json}" --config .prettierrc
                - pnpm tsc --noEmit
                - pnpm lint
                - echo "✅ Qualité du code backend validée"

          - step:
              name: Frontend - Code Quality
              caches:
                - pnpm
              script:
                - npm install -g pnpm
                - cd frontend
                - echo "🔍 Vérification de la qualité du code frontend..."
                - pnpm prettier --check "src/**/*.{ts,tsx,js,jsx,json,css}" --config .prettierrc
                - pnpm tsc --noEmit
                - pnpm lint
                - echo "✅ Qualité du code frontend validée"

          - step:
              name: Shared - Code Quality
              caches:
                - pnpm
              script:
                - npm install -g pnpm
                - cd shared
                - echo "🔍 Vérification de la qualité du code shared..."
                - pnpm prettier --check "**/*.{ts,js,json}" --config .prettierrc
                - pnpm lint
                - echo "✅ Qualité du code shared validée"
